[package]
name = "rsmpeg"
version = "0.1.0"
edition = "2021"
author = "lapingenieur"

[alias]
w = "build --target x86_64-pc-windows-gnu"

[dependencies]
eframe = "0.18.0"
rfd = "0.8.2"
strum = "0.24.0"
strum_macros = "0.24.0"
